version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - mvn -B help:evaluate -Dexpression=project.version -q -DforceStdout=true > version.txt
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - mvn install
      - npm install
  build:
    commands:
      - mvn clean package -Pproduction
      - VERSION=$(cat version.txt)
      - cp target/BesserTanken-${VERSION}-exec.jar BesserTanken-${VERSION}-exec.jar
      - rm -r target
artifacts:
  files:
    - '**/*-exec.jar'
