openapi: 3.0.3
info:
  title: BesserTanken
  description: Openapi definition for BesserTanken.
  version: 1.0.0
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'

paths:
  /dummy:
    get:
      summary: Dummy endpoint
      operationId: getDummy
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Hello, World!'
