openapi: 3.0.3
info:
  title: BesserTanken
  description: Openapi definition for BesserTanken.
  version: 1.0.0
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: 'localhost:7070'

paths:
